### ISSUE TITLE
account closing fails with `ECONNREFUSED 127.0.0.1:443`

### ISSUE THREAD

**Issue by s0enke** [superwerker/aws-organizations-vending-machine#21]
Looks like a strange node/js dependency issue?

```
Error: connect ECONNREFUSED 127.0.0.1:443 Stack: Error: connect ECONNREFUSED 127.0.0.1:443    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:126:14) for step: loginToAccount
ERROR: 1 step failed while executing the canary
```

Maybe related:

 - https://github.com/facebook/jest/issues/10784

**Comment by s0enke** [comment]
fixed by https://github.com/superwerker/mavm/commit/afd019f140006dab43bcc00a4d47de0547aed215
